# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Eazi iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
     pod 'XMPPFramework'
	pod 'JSQMessagesViewController'
     pod 'SQLite.swift'
     pod 'IQKeyboardManagerSwift'
	pod 'Alamofire'
     pod 'SwiftyJSON'
     pod 'MBProgressHUD', '~> 1.0.0'
     pod 'DropDown'


  end
